### ISSUE TITLE
midpoint integration in velPosPreintLPMPartial

### ISSUE THREAD

**Issue by hannibal051** [UTS-CAS/ugpm#4]
When the IMU measurement time is not continuous in most cases, you choose midpoint integration to deal with the continuous function 0.5*a*t^2.
However, the code is `(2.0*d_0 + d_1) / 3` for 2/3 point of acceleration. I modify it to `(d_0 + d_1) / 2` and find no difference. So I wonder why you choose 2/3 point?

**Comment by clegenti** [comment]
Hi,

I am sorry but I cannot find the operation that you are mentioning (line number?).

If you are referring to `...(2.0*d_0 + d_1)/6.0);` on lines 645 and 671 of `preintegration.cpp`, it is the double integral (from acceleration to position directly) based on the assumption that the acceleration is an affine function of time between t_0 and t_1.

**Comment by hannibal051** [comment]
Thank you for your answer.
My question is why you choose (2*a_0+a1)/3 instead of (a_0+a_1)/2 ?
Besides, to get bias value in continuous time, you also use linear interpolation. I modify the integration of accelerations to (a_0+a_1)/2, the bias value to value of the nearest time stamp. The results (preintegration accuracy) remain similar.

**Comment by clegenti** [comment]
I do use the midpoint for the velocity (d0+d1)/2. But I am not sure about the (2*a_0+a1)/3. 
Sorry but I really can't find a place in `preintegration.cpp` where such a thing would happen.
Can you give me the line number where this happens?

**Comment by hannibal051** [comment]
Cause I add many comments in the code, the function is velPosPreintLPM.

**Comment by clegenti** [comment]
I cannot find any division by 3 in `velPosPreintLPM` nor `velPosPreintLPMPartial`, only divisions by 2 for the velocities and division by 6 for the positions.

**Comment by hannibal051** [comment]
Yeah I mean the division by 6. That's 0.5at^2, so I cannot understand why division by 6, instead of (d_d_0_d_bf + d_d_1_d_bf) / 4? My same question hold for the function velPosPreintLPMPartial.

**Comment by clegenti** [comment]
Here are screenshots of the lines I believe you are referring to:
![integration](https://user-images.githubusercontent.com/18108165/221483498-e750c312-5aca-4303-90a3-a56f42f52ca7.png)
and
![bias_integration](https://user-images.githubusercontent.com/18108165/221483594-20981424-8e8c-4e4a-b1a3-6e5b57cabc36.png)

There is no `0.5`.

I made this little Matlab script to show how you can derive these coefficients
```matlab
% Definition of the symbolic variables
% The two data points
data_t = sym('data_t', [2,1],'real');
% The corresponding time stamps
data_f = sym('data_f', [2,1],'real');
% Time
t = sym('t', [1,1], 'real');

% Getting the parameters of alpha*t + beta = f
alpha = (data_f(2) - data_f(1)) / (data_t(2)-data_t(1));
beta = data_f(1) - (alpha*data_t(1));

f = alpha*t + beta;

% Integration between t_0 and t_1 for velocity
vel_0_to_1 = int(f, t, data_t(1), data_t(2))

% Integration between t_0 and t_1 for position (first need the integration
% between t_0 and t for the velocity at time t)
vel_0_to_t = int(f, t, data_t(1), t);
pos_0_to_1 = int(vel, t, data_t(1), data_t(2))
```

and here is the output
```
vel_0_to_1 = -((data_f1 + data_f2)*(data_t1 - data_t2))/2
  
pos_0_to_1 = ((2*data_f1 + data_f2)*(data_t1 - data_t2)^2)/6
```

**Comment by hannibal051** [comment]
Thank you very much for your patience. Sorry for confusion about (traditional) midpoint/euler integration with the continuous one.

**Comment by hannibal051** [comment]
Thank you very much for your patience. The continuous linear interpolation is used in the continuous integration.

**Comment by clegenti** [comment]
No worries, I am glad to see people interested in our work :)

I am closing the issue.
